# Generated by Django 2.1.7 on 2019-03-21 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('department', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('usn', models.CharField(max_length=240)),
                ('email', models.EmailField(max_length=254)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.CollegeClass')),
            ],
        ),
    ]
