# Generated by Django 2.1.7 on 2019-03-21 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='management.CollegeClass'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=240),
        ),
        migrations.AlterField(
            model_name='student',
            name='usn',
            field=models.CharField(default='', max_length=240),
        ),
    ]
