# Generated by Django 2.1.7 on 2019-03-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20190321_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='usn',
            field=models.CharField(default='', max_length=240, primary_key=True, serialize=False),
        ),
    ]
