# Generated by Django 2.2 on 2019-04-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20190409_1052'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('period', 'student')},
        ),
    ]
