# Generated by Django 2.2 on 2019-04-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20190409_1107'),
        ('management', '0003_auto_20190409_1114'),
    ]

    operations = [
    ]
