# Generated by Django 2.2 on 2019-04-11 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_merge_20190411_1109'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
    ]
