# Generated by Django 2.1.7 on 2019-03-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20190321_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeclass',
            name='department',
            field=models.CharField(max_length=200),
        ),
    ]
