# Generated by Django 2.1.7 on 2019-03-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=240)),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
