# Generated by Django 2.2 on 2019-04-11 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20190411_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('period', 'student')},
        ),
    ]
