# Generated by Django 2.1.7 on 2019-03-21 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20190321_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('college_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.CollegeClass')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.TimeSlot')),
            ],
        ),
    ]
