# Generated by Django 2.1.7 on 2019-03-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
