# Generated by Django 2.1.7 on 2019-03-21 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_auto_20190321_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.Period')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.Student')),
            ],
        ),
    ]
