# Generated by Django 2.1.7 on 2019-03-21 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='date',
        ),
    ]
