# Generated by Django 2.1.7 on 2019-04-04 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_remove_period_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='college_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.CollegeClass'),
        ),
        migrations.AlterField(
            model_name='period',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Subject'),
        ),
    ]
