# Generated by Django 2.1.7 on 2019-04-05 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_auto_20190404_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken', models.BooleanField(default=False)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.Period')),
            ],
        ),
    ]
