# Generated by Django 2.1.7 on 2019-04-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_periodtracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='present_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
