# Generated by Django 2.2 on 2019-04-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('usn', models.CharField(max_length=240, primary_key=True, serialize=False)),
                ('person_id', models.CharField(max_length=240)),
            ],
        ),
    ]
